---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
   - name: postgres
     port: 5432
     protocol: TCP
     targetPort: postgresql-tcp
  selector:
    app: postgresql
