---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connexion-app-configmap
  labels:
    app: connexion-app
data:
  POSTGRES_DB: connexionapp
  POSTGRES_HOSTNAME: postgresql-svc
  POSTGRES_PORT: "5432"
  FLASK_DEBUG: "False"
  FLASK_APP: "wsgi:app"
  CHECK_MIGRATION: "True"
