---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: connexion-app-hpa
  labels:
    app: connexion-app
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: connexion-app-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
