bases:
  - ./../../base
namespace: development
commonLabels:
  namespace: development
patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
- job.yaml
resources:
- secret.yaml
- ingress.yaml
- namespace.yaml
